### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by iwashi** [twajp/TokoBus#1]
@twajp 
実際の課題からアイデアを抽出して作成されている、かつ課題要件を大きく超えてリリースまでされており大変素晴らしい提出でした。
課題提出お疲れさまでした！

本IssueはいつでもcloseいただいてOKです。

**Comment by twajp** [comment]
@iwashi 
ありがとうございます。
先生の講義はとてもためになる内容でした。
これからも学んだ事を活かして、様々な課題を解決できるよう力をつけていきたいと思います。
